services:
  pulsar-auth:
    image: apachepulsar/pulsar:3.2.0
    container_name: pulsar-auth
    ports:
      - "6651:6650"
      - "8081:8080"
    environment:
      - PULSAR_MEM=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g
      - PULSAR_STANDALONE_USE_ZOOKEEPER=true
      - PULSAR_STANDALONE_RESET=true
      - PULSAR_LOG_CONF=/pulsar/conf/log4j2.yaml
      - PULSAR_LOG_APPENDER=Console
    command: |
      bash -lc '
        set -e
        set -x
        if [ ! -f /pulsar/conf/secret.key ]; then
          bin/pulsar tokens create-secret-key --output /pulsar/conf/secret.key
        fi
        if [ ! -f /pulsar/conf/admin.token ]; then
          bin/pulsar tokens create --secret-key /pulsar/conf/secret.key --subject admin > /pulsar/conf/admin.token
        fi
        if [ ! -f /pulsar/conf/client.token ]; then
          bin/pulsar tokens create --secret-key /pulsar/conf/secret.key --subject client > /pulsar/conf/client.token
        fi
        echo "Starting Pulsar Standalone service..."
        bin/pulsar standalone --no-functions-worker
      '
    tmpfs:
      - /pulsar/data:rw,noexec,nosuid,size=1g
    networks:
      - pulsar-net
    restart: unless-stopped

networks:
  pulsar-net:
    driver: bridge