services:
  pulsar:
    image: apachepulsar/pulsar:3.2.0
    container_name: pulsar
    ports:
      - "6650:6650"
      - "8081:8080"  # ← Use 8081 instead of 8080
    environment:
      - PULSAR_MEM=-Xms512m -Xmx512m
      - PULSAR_STANDALONE_USE_ZOOKEEPER=true
      - PULSAR_STANDALONE_RESET=true  # ← Force reset on startup
    command: bin/pulsar standalone
    healthcheck:
      test: ["CMD", "bin/pulsar-admin", "brokers", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 120s
    volumes:
      - /tmp/pulsar-data:/pulsar/data  # ← Use temp storage for CI

  toxiproxy:
    image: ghcr.io/shopify/toxiproxy:2.11.0
    container_name: toxiproxy
    ports:
      - "8475:8474"  # ← Use 8475 instead of 8474
      - "16650:16650"
    # No healthcheck possible - this is a distroless container
    depends_on:
      pulsar:
        condition: service_healthy