version: '3.8'

services:
  # Zookeeper
  zookeeper:
    image: apachepulsar/pulsar:4.0.0
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    command: bin/pulsar zookeeper
    environment:
      - PULSAR_MEM=-Xms256m -Xmx256m
    healthcheck:
      test: ["CMD", "bin/pulsar-zookeeper-ruok.sh"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s
    tmpfs:
      - /pulsar/data:rw,noexec,nosuid,size=256m
    networks:
      - pulsar-cluster
    restart: unless-stopped
  pulsar-init:
    image: apachepulsar/pulsar:4.0.0
    container_name: pulsar-init
    hostname: pulsar-init
    working_dir: /pulsar
    command: >
      bin/pulsar initialize-cluster-metadata
        --cluster cluster-a
        --zookeeper zookeeper:2181
        --configuration-store zookeeper:2181
        --web-service-url http://broker:8080
        --broker-service-url pulsar://broker:6650
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - pulsar-cluster
    restart: "no"

  # BookKeeper
  bookkeeper:
    image: apachepulsar/pulsar:4.0.0
    container_name: bookkeeper
    hostname: bookkeeper
    ports:
      - "3181:3181"
    command: bin/pulsar bookie
    environment:
      - PULSAR_MEM=-Xms512m -Xmx512m
      - PULSAR_GC=-XX:+UseG1GC
      - zkServers=zookeeper:2181
      - clusterName=cluster-a
      - metadataServiceUri=zk:zookeeper:2181
      - journalDirectory=/pulsar/data/journal
      - ledgersDirectory=/pulsar/data/ledgers
    depends_on:
      zookeeper:
        condition: service_healthy
      pulsar-init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 3181"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 120s
    tmpfs:
      - /pulsar/data/journal:rw,noexec,nosuid,size=512m
      - /pulsar/data/ledgers:rw,noexec,nosuid,size=1g
    networks:
      - pulsar-cluster
    restart: unless-stopped

  # Pulsar Broker
  broker:
    image: apachepulsar/pulsar:4.0.0
    container_name: broker
    hostname: broker
    ports:
      - "6650:6650"
      - "8080:8080"
    command: bin/pulsar broker
    environment:
      - PULSAR_MEM=-Xms512m -Xmx512m
      - zookeeperServers=zookeeper:2181
      - clusterName=cluster-a
      - advertisedAddress=broker
      - advertisedListeners=pulsar://broker:6650
    depends_on:
      zookeeper:
        condition: service_healthy
      bookkeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "bin/pulsar-admin", "brokers", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s
    networks:
      - pulsar-cluster
    restart: unless-stopped

networks:
  pulsar-cluster:
    driver: bridge