version: '3.8'

services:
  pulsar:
    image: apachepulsar/pulsar:3.2.0
    container_name: pulsar
    ports:
      - "6650:6650"
      - "8080:8080"
    environment:
      - PULSAR_MEM=-Xms512m -Xmx512m
      - PULSAR_STANDALONE_USE_ZOOKEEPER=true
    command: bin/pulsar standalone
    healthcheck:
      test: ["CMD", "bin/pulsar-admin", "brokers", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 120s
    networks:
      - testing-net

  toxiproxy:
    image: ghcr.io/shopify/toxiproxy:2.11.0
    container_name: toxiproxy
    ports:
      - "8474:8474"
      - "16650:16650"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8474/version"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 240s
    networks:
      - testing-net

networks:
  testing-net:
    driver: bridge