services:
  pulsar:
    image: apachepulsar/pulsar:3.2.0
    container_name: pulsar
    ports:
      - "6650:6650"
      - "8081:8080"  # ← Use 8081 instead of 8080
    environment:
      - PULSAR_MEM=-Xms512m -Xmx512m
      - PULSAR_STANDALONE_USE_ZOOKEEPER=true
      - PULSAR_STANDALONE_RESET=true  # ← Force reset on startup
    command: bin/pulsar standalone
    tmpfs:
      - /pulsar/data:rw,noexec,nosuid,size=1g  # ← Replace volume with tmpfs
    healthcheck:
      test: ["CMD", "bash", "-lc", "curl -sf http://localhost:8080/admin/v2/brokers/health >/dev/null"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 20s

  toxiproxy:
    image: ghcr.io/shopify/toxiproxy:2.11.0
    container_name: toxiproxy
    ports:
      - "8474:8474"
      - "16650:16650"
    # No healthcheck possible - this is a distroless container
    depends_on:
      pulsar:
        condition: service_healthy