name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    name: ${{ matrix.artifact-name }}
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        include:
          - artifact-name: pulsar-client-linux-static-musl-aarch64
            os: ubuntu-22.04-arm
            container: swift:6.1.0
            swift-sdk: aarch64-swift-linux-musl
            swift-sdk-url: https://download.swift.org/swift-6.1-release/static-sdk/swift-6.1-RELEASE/swift-6.1-RELEASE_static-linux-0.0.1.artifactbundle.tar.gz
            swift-sdk-checksum: 111c6f7d280a651208b8c74c0521dd99365d785c1976a6e23162f55f65379ac6
            product: PulsarClient
          - artifact-name: pulsar-client-linux-static-musl-x86_64
            os: ubuntu-22.04-arm
            container: swift:6.1.0
            swift-sdk: x86_64-swift-linux-musl
            swift-sdk-url: https://download.swift.org/swift-6.1-release/static-sdk/swift-6.1-RELEASE/swift-6.1-RELEASE_static-linux-0.0.1.artifactbundle.tar.gz
            swift-sdk-checksum: 111c6f7d280a651208b8c74c0521dd99365d785c1976a6e23162f55f65379ac6
            product: PulsarClient
          - artifact-name: pulsar-client-macos-arm64
            os: macos-15
            xcode-select: /Applications/Xcode_16.3.app
            product: PulsarClient
    
    steps:
    - uses: actions/checkout@v4
    - name: Install Static Linux SDK
      if: ${{ matrix.swift-sdk-url != '' }}
      run: |
        swift sdk install ${{ matrix.swift-sdk-url }} --checksum ${{ matrix.swift-sdk-checksum }}
    - name: xcode-select
      if: ${{ matrix.xcode-select != '' }}
      run: |
        sudo xcode-select --switch ${{ matrix.xcode-select }}
    - name: Build
      shell: bash
      run: |
        args=(
          --configuration release
          --product "${{ matrix.product }}"
        )

        if [ -n "${{ matrix.swift-sdk }}" ]; then
          args+=(--swift-sdk "${{ matrix.swift-sdk }}")
        fi

        swift build "${args[@]}"
    - name: Run Unit Tests
      run: swift test --filter PulsarClientTests
    
  integration-tests:
    name: Integration Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - artifact-name: pulsar-client-linux-static-musl-aarch64
            os: ubuntu-22.04-arm
            swift-version: '6.1'
            product: PulsarClient
    steps:
    - uses: actions/checkout@v4
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ matrix.swift-version }}
        skip-signature-check: true

    - name: Start Pulsar and Toxiproxy
      run: |
        # Start Pulsar
        docker run -d \
          --name pulsar-test \
          --network host \
          -e PULSAR_MEM="-Xms512m -Xmx512m" \
          -e PULSAR_STANDALONE_USE_ZOOKEEPER="true" \
          apachepulsar/pulsar:3.2.0 \
          bin/pulsar standalone
        
        # Start Toxiproxy
        docker run -d \
          --name toxiproxy-test \
          --network host \
          ghcr.io/shopify/toxiproxy:2.11.0
        
        # Wait for Pulsar to be ready
        echo "Waiting for Pulsar to be ready..."
        timeout 180 bash -c 'until docker exec pulsar-test bin/pulsar-admin brokers healthcheck; do sleep 5; echo "Still waiting..."; done'
        echo "Pulsar is ready!"
        
        # Wait for Toxiproxy to be ready
        echo "Waiting for Toxiproxy to be ready..."
        timeout 60 bash -c 'until curl -f http://localhost:8474/version; do sleep 2; echo "Still waiting..."; done'
        echo "Toxiproxy is ready!"
    
    - name: Configure Toxiproxy
      run: |
        # Create proxy for Pulsar
        curl -X POST http://localhost:8474/proxies \
          -H 'Content-Type: application/json' \
          -d '{
            "name": "pulsar",
            "listen": "0.0.0.0:16650",
            "upstream": "localhost:6650",
            "enabled": true
          }'
        echo "Toxiproxy configured successfully"
    
    - name: Run Integration Tests
      env:
        PULSAR_SERVICE_URL: pulsar://localhost:6650
        PULSAR_ADMIN_URL: http://localhost:8080
        TOXIPROXY_URL: http://localhost:8474
      run: swift test --filter PulsarClientIntegrationTests
    
    - name: Cleanup
      if: always()
      run: |
        docker stop pulsar-test toxiproxy-test || true
        docker rm pulsar-test toxiproxy-test || true

  integration-tests-auth:
    name: Integration Tests with Authentication
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - artifact-name: pulsar-client-linux-static-musl-aarch64
            os: ubuntu-22.04-arm
            swift-version: '6.1'
            product: PulsarClient
    steps:
    - uses: actions/checkout@v4
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ matrix.swift-version }}
        skip-signature-check: true
    
    - name: Start Pulsar with Auth
      run: |
        docker compose -f docker/docker-compose.auth.yml up -d
        # Wait for Pulsar to be ready
        timeout 180 bash -c 'until curl -f http://localhost:8081/admin/v2/brokers/health; do sleep 5; echo "Still waiting..."; done'
    
    - name: Get Auth Token
      id: auth
      run: |
        TOKEN=$(docker exec pulsar-auth cat /pulsar/conf/client.token)
        echo "token=$TOKEN" >> $GITHUB_OUTPUT
    
    - name: Run Integration Tests
      env:
        PULSAR_SERVICE_URL: pulsar://localhost:6651
        PULSAR_ADMIN_URL: http://localhost:8081
        PULSAR_AUTH_TOKEN: ${{ steps.auth.outputs.token }}
      run: swift test --filter PulsarClientIntegrationTests
    
    - name: Cleanup
      if: always()
      run: docker compose -f docker/docker-compose.auth.yml down -v

  integration-tests-cluster:
    name: Integration Tests with Cluster
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - artifact-name: pulsar-client-linux-static-musl-aarch64
            os: ubuntu-22.04-arm
            swift-version: '6.1'
            product: PulsarClient
    steps:
    - uses: actions/checkout@v4
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ matrix.swift-version }}
        skip-signature-check: true
    
    - name: Start Pulsar Cluster
      run: |
        docker compose -f docker/docker-compose.cluster.yml up -d
        # Wait for cluster to be ready
        timeout 180 bash -c 'until curl -f http://localhost:8080/admin/v2/brokers/health; do sleep 5; echo "Still waiting..."; done'
    
    - name: Run Integration Tests
      env:
        PULSAR_SERVICE_URL: pulsar://localhost:6650
        PULSAR_ADMIN_URL: http://localhost:8080
      run: swift test --filter PulsarClientIntegrationTests
    
    - name: Cleanup
      if: always()
      run: docker compose -f docker/docker-compose.cluster.yml down -v
