name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ['6.1']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ matrix.swift }}
    
    - name: Run Unit Tests
      run: swift test --filter PulsarClientTests

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    
    services:
      # Pulsar service
      pulsar:
        image: apachepulsar/pulsar:3.2.0
        ports:
          - 6650:6650
          - 8080:8080
        env:
          PULSAR_MEM: -Xms512m -Xmx512m
          PULSAR_STANDALONE_USE_ZOOKEEPER: "true"
        options: >-
          --health-cmd "curl -f http://localhost:8080/admin/v2/brokers/health || exit 1"
          --health-interval 30s
          --health-timeout 10s
          --health-retries 3
          --health-start-period 120s
        
      # Toxiproxy service for failure testing
      toxiproxy:
        image: ghcr.io/shopify/toxiproxy:2.11.0
        ports:
          - 8474:8474
        options: >-
          --health-cmd "curl -s http://localhost:8474/version || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
          --health-start-period 30s
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '6.1'
    
    - name: Wait for Pulsar
      run: |
        echo "Waiting for Pulsar to be ready..."
        timeout 180 bash -c 'until curl -f http://localhost:8080/admin/v2/brokers/health; do sleep 5; echo "Still waiting..."; done'
        echo "Pulsar is ready!"
    
    - name: Wait for Toxiproxy
      run: |
        echo "Waiting for Toxiproxy to be ready..."
        timeout 60 bash -c 'until curl -f http://localhost:8474/version; do sleep 2; echo "Still waiting..."; done'
        echo "Toxiproxy is ready!"
    
    - name: Configure Toxiproxy
      run: |
        # Create proxy for Pulsar
        curl -X POST http://localhost:8474/proxies \
          -H 'Content-Type: application/json' \
          -d '{
            "name": "pulsar",
            "listen": "0.0.0.0:16650",
            "upstream": "pulsar:6650",
            "enabled": true
          }'
        echo "Toxiproxy configured successfully"
    
    - name: Run Integration Tests
      env:
        PULSAR_SERVICE_URL: pulsar://localhost:6650
        PULSAR_ADMIN_URL: http://localhost:8080
        TOXIPROXY_URL: http://localhost:8474
      run: swift test --filter IntegrationTests

  integration-tests-auth:
    name: Integration Tests with Authentication
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '6.1'
    
    - name: Start Pulsar with Auth
      run: |
       run: |
        docker compose -f docker/docker-compose.auth.yml up -d
        # Wait for Pulsar to be ready
        timeout 180 bash -c 'until curl -f http://localhost:8081/admin/v2/brokers/health; do sleep 5; echo "Still waiting..."; done'
    
    - name: Get Auth Token
      id: auth
      run: |
        TOKEN=$(docker exec pulsar-auth cat /pulsar/conf/client.token)
        echo "token=$TOKEN" >> $GITHUB_OUTPUT
    
    - name: Run Integration Tests
      env:
        PULSAR_SERVICE_URL: pulsar://localhost:6651
        PULSAR_ADMIN_URL: http://localhost:8081
        PULSAR_AUTH_TOKEN: ${{ steps.auth.outputs.token }}
      run: swift test --filter IntegrationTests
    
    - name: Cleanup
      if: always()
      run: docker compose -f docker/docker-compose.auth.yml down -v

  integration-tests-cluster:
    name: Integration Tests with Cluster
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '6.1'
    
    - name: Start Pulsar Cluster
      run: |
        docker compose -f docker/docker-compose.cluster.yml up -d
        # Wait for cluster to be ready
        timeout 180 bash -c 'until curl -f http://localhost:8080/admin/v2/brokers/health; do sleep 5; echo "Still waiting..."; done'
    
    - name: Run Integration Tests
      env:
        PULSAR_SERVICE_URL: pulsar://localhost:6650
        PULSAR_ADMIN_URL: http://localhost:8080
      run: swift test --filter IntegrationTests
    
    - name: Cleanup
      if: always()
      run: docker compose -f docker/docker-compose.cluster.yml down -v